<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Education_Type</name>
   <tag></tag>
   <elementGuidId>a9dc976c-e2e5-4722-8679-646d7f0c02c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;educationType_block_Iqhvwe&quot;)/div[@class=&quot;multiinput&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'educationType_block_')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiinput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;educationType_block_Iqhvwe&quot;)/div[@class=&quot;multiinput&quot;]</value>
   </webElementProperties>
</WebElementEntity>
